package tester

import (
	"fmt"
	"strings"
	"time"
)

// Report is the aggregated test report for all modules.
type Report struct {
	// Modules lists the results per module.
	Modules []TestResult

	// TotalModules is the number of modules tested.
	TotalModules int

	// PassedModules is the number of modules whose tests all passed.
	PassedModules int

	// FailedModules is the number of modules with test failures.
	FailedModules int

	// ErrorModules is the number of modules that could not be tested (errors).
	ErrorModules int

	// TotalDuration is the wall-clock time for the entire test run.
	TotalDuration time.Duration

	// AllPassed is true only if every module passed.
	AllPassed bool
}

// BuildReport aggregates individual test results into a Report.
func BuildReport(results []TestResult, totalDuration time.Duration) *Report {
	r := &Report{
		Modules:       results,
		TotalModules:  len(results),
		TotalDuration: totalDuration,
	}

	for _, res := range results {
		switch {
		case res.Error != nil:
			r.ErrorModules++
		case res.Passed:
			r.PassedModules++
		default:
			r.FailedModules++
		}
	}

	r.AllPassed = r.FailedModules == 0 && r.ErrorModules == 0
	return r
}

// FormatMarkdown renders the report as a GitHub-flavored Markdown string
// suitable for posting as a PR comment.
func (r *Report) FormatMarkdown() string {
	var b strings.Builder

	// Header
	if r.AllPassed {
		fmt.Fprintf(&b, "## ✅ Fleet Test Report — All Passed\n\n")
	} else {
		fmt.Fprintf(&b, "## ❌ Fleet Test Report — Failures Detected\n\n")
	}

	// Summary table
	fmt.Fprintf(&b, "| Metric | Count |\n")
	fmt.Fprintf(&b, "|--------|-------|\n")
	fmt.Fprintf(&b, "| Modules tested | %d |\n", r.TotalModules)
	fmt.Fprintf(&b, "| Passed | %d |\n", r.PassedModules)
	fmt.Fprintf(&b, "| Failed | %d |\n", r.FailedModules)
	fmt.Fprintf(&b, "| Errors | %d |\n", r.ErrorModules)
	fmt.Fprintf(&b, "| Duration | %s |\n", r.TotalDuration.Round(time.Millisecond))
	fmt.Fprintln(&b)

	// Per-module details
	for _, res := range r.Modules {
		icon := "✅"
		if res.Error != nil {
			icon = "⚠️"
		} else if !res.Passed {
			icon = "❌"
		}

		agentTag := ""
		if res.AgentGenerated {
			agentTag = " 🤖"
		}

		fmt.Fprintf(&b, "### %s `%s`%s\n\n", icon, res.Module.RelPath, agentTag)
		fmt.Fprintf(&b, "**Duration:** %s\n\n", res.Duration.Round(time.Millisecond))

		if res.Error != nil {
			fmt.Fprintf(&b, "**Error:** `%s`\n\n", res.Error.Error())
		}

		if res.Output != "" {
			output := SummarizeOutput(res.Output, 50)
			fmt.Fprintf(&b, "<details>\n<summary>Test output</summary>\n\n```\n%s\n```\n\n</details>\n\n", strings.TrimRight(output, "\n"))
		}
	}

	// Footer
	fmt.Fprintf(&b, "---\n*Generated by `fleet test`*\n")

	return b.String()
}

// FormatTerminal renders a compact report for terminal display.
func (r *Report) FormatTerminal() string {
	var b strings.Builder

	for _, res := range r.Modules {
		icon := "✓"
		if res.Error != nil {
			icon = "⚠"
		} else if !res.Passed {
			icon = "✗"
		}

		agentTag := ""
		if res.AgentGenerated {
			agentTag = " (agent-generated)"
		}

		fmt.Fprintf(&b, "  %s  %-40s %s%s\n", icon, res.Module.RelPath, res.Duration.Round(time.Millisecond), agentTag)
	}

	fmt.Fprintln(&b)
	if r.AllPassed {
		fmt.Fprintf(&b, "  All %d modules passed (%s)\n", r.TotalModules, r.TotalDuration.Round(time.Millisecond))
	} else {
		fmt.Fprintf(&b, "  %d/%d passed, %d failed, %d errors (%s)\n",
			r.PassedModules, r.TotalModules, r.FailedModules, r.ErrorModules,
			r.TotalDuration.Round(time.Millisecond))
	}

	return b.String()
}
